export const STYLES = {
  container: {
    position: 'fixed' as const,
    bottom: '16px',
    right: '16px',
    zIndex: 99999,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace',
    fontSize: '13px',
    color: '#e4e4e7',
  },
  containerLeft: {
    right: 'auto',
    left: '16px',
  },
  toggleButton: {
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    border: '1px solid #3f3f46',
    background: '#18181b',
    color: '#a1a1aa',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.4)',
  },
  panel: {
    width: '480px',
    maxHeight: '400px',
    background: '#18181b',
    border: '1px solid #3f3f46',
    borderRadius: '8px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid #3f3f46',
    background: '#09090b',
  },
  tab: {
    padding: '8px 16px',
    border: 'none',
    background: 'transparent',
    color: '#71717a',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 500,
    borderBottom: '2px solid transparent',
  },
  tabActive: {
    color: '#e4e4e7',
    borderBottomColor: '#3b82f6',
  },
  panelContent: {
    padding: '12px',
    overflowY: 'auto' as const,
    maxHeight: '340px',
    flex: 1,
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '12px',
  },
  th: {
    textAlign: 'left' as const,
    padding: '6px 8px',
    borderBottom: '1px solid #27272a',
    color: '#a1a1aa',
    fontWeight: 600,
  },
  td: {
    padding: '6px 8px',
    borderBottom: '1px solid #27272a',
    maxWidth: '160px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  button: {
    padding: '6px 12px',
    borderRadius: '4px',
    border: '1px solid #3f3f46',
    background: '#27272a',
    color: '#e4e4e7',
    cursor: 'pointer',
    fontSize: '12px',
  },
  buttonDanger: {
    background: '#7f1d1d',
    borderColor: '#991b1b',
  },
  badge: {
    display: 'inline-block',
    padding: '2px 6px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 600,
  },
  badgeSuccess: {
    background: '#14532d',
    color: '#4ade80',
  },
  badgeError: {
    background: '#7f1d1d',
    color: '#f87171',
  },
  emptyState: {
    color: '#71717a',
    textAlign: 'center' as const,
    padding: '24px',
    fontSize: '12px',
  },
  label: {
    color: '#a1a1aa',
    fontSize: '11px',
    marginBottom: '4px',
  },
  value: {
    color: '#e4e4e7',
    fontSize: '13px',
    marginBottom: '12px',
    wordBreak: 'break-all' as const,
  },
};
